import React from 'react'

class Prepping extends React.Component{
  constructor(){
    super()

    this.state = {}
  }

  render(){
    return(
      <div className='prepping'>
        <div className='section-title'>Prepping for the Multi-Platform Release</div>
        <div className='text'>

          <img src='../../assets/pics/prepping/snowpiercer.jpeg'/>
          <img src='../../assets/pics/prepping/Okja.jpg'/>

          <p>When the Weinstein Company pondered whether to cut twenty minutes off Bong Joon-Ho’s Snowpiercer in 2013, they backed off after a wave of critical disapproval. The company had intended to make edits to the film that fit into their views and policies on film duration and tempo (Vulture 2013). The Weinsteins are notorious for making major changes in post production to both the edit and the soundtrack, and the developments had infuriated Bong (Guardian 2013). So, It is not surprising that for his next film, Okja, Bong decided to work with Netflix, a deep-pocketed patron valued for their reputation as non-intrusive financiers. Netflix has been heavily spending on original content and offering a ‘hands off the creatives’ policy in order to attract big names to their brand, and they have succeeded in this regard with recent productions such as Mindhunter with David Fincher, The Ballad of Buster Scruggs with Coen Brothers, as well as Godless with Steven Soderbergh (Netflix 2017).</p><br/>


          <p>According to Bong Joon-Ho What Netflix offered him was very enticing, “(They) guaranteed my complete freedom in terms of putting together my team and the final cut privilege” He said, which “Only god-like filmmakers such as Spielberg get” (Variety 2017). In addition to creative freedom, Okja has a budget of $50 million, which is similar to the amount paid for the whole season of House of Cards or Orange is the New Black. With Bong’s reputation, It turned into a star-studded international co-production. Okja is just one of Netflix’s many investments in original production in a short period of time. Recently they acquired indie comic book publisher Millarworld, which contained titles such as Kingsman and Kick-Ass, however, rights for the two hit films were not included in the deal (Netflix 2017), so the acquisition is really an investment for their other intellectual properties that have potential to be part of their original content. The platform’s emphasis on creative originality is reflected by their funding of a wide variety of genres to their library. Other than their award-winning original drama series, they also found hits in a variety of smaller genres from Making a Murderer (Documentary), Unbreakable Kimmy Schmidt (Comedy) to Bojack Horseman (Adult Animation). The all-encompassing nature of their investment strategy is economically very high risk, as the nature of film and television production is high up-front investment and with little guarantee of return. Whether Netflix’s aggressive investment agenda will pay off in the long run (The company reportedly in long term debt of over $4 billion) (Variety 2017) remains to be seen. However, CEO Reed Hastings noted that Netflix’s ratio of debt to its market capitalization, which is around $80 billion, is low enough to allay any concerns (Fortune 2017). The platform is expected to spend $6 billion in content programming in 2017 (Geekwire 2017). Despite the risks within this investment model, the company is receiving positive results: its share price rocketed 64% over the past year, subscriber count increased to 103 million (More than half from outside US) and its original productions received 91 Emmy nominations (Guardian 2017). The potential revenue streams further down the line is also exciting, with their original series being some of the most popular television series at present, they are looking to expand into the merchandise market (Bloomberg 2017), in an attempt to maximise profits from the ancillary rights.</p><br/>

          <img src='../../assets/pics/prepping/houseofcards.jpg'/>
          <img src='../../assets/pics/prepping/oitnb.jpeg'/>
          <img src='../../assets/pics/prepping/makingamurderer.jpg'/>
          <img src='../../assets/pics/prepping/bojack.jpg'/>

          <p>In the case of Amazon, the multi-billion delivery business, their venture into video-on-demand had been substantial. Their VOD platform, Amazon Video, was established in 2006, with their film distribution/production company, Amazon Studios, established in 2010. They are taking a similar approach in original production as Netflix. Investing in a wide range of genres such as the critically-acclaimed Nazi-Japanese thriller The Man in the High Castle, an alternative, dystopian take on World War II, Comrade Detective, a comedy starring Joseph Gordon-Levitt and Channing Tatum, as well as The Grand Tour, the motoring television series presented by Jeremy Clarkson, Richard Hammond and James May, the original presenters for Top Gear, an extremely popular series on the BBC. Despite not having quite as wide a range or sheer volume of hits as Netflix, Amazon has the extra attraction for subscribers with the practicality of fast delivery of goods purchased from their online marketplace, as well as Prime Music, a streaming catalogue for over two million songs. There are no reports on the exact amount of Amazon Prime subscribers worldwide, but in the US alone they have 79 million subscribers, so the worldwide count is likely to be much higher than Netflix’s. Based on the multi-faceted nature of the Amazon Prime subscription, there are many reasons for a consumer to subscribe to the platform. With the size of their subscriber base it shows a tremendous amount of potential for Amazon’s SVOD platform, because given Amazon’s other assets, their financial stability at present is far higher than of Netflix’s. The platform is expected to spend $4.5 billion in content programming in 2017. Both Netflix and Amazon have been exponentially increasing their programming spend every year (Geekwire 2017). The competition is clear as both platforms race to attract subscribers with their programming.</p><br/>

          <p>On the other hand, both front-runners of the SVOD business are making a positive impact on film and television content in the market as they are producing some of the most talked-about television drama in the world at present exclusive on SVOD. The platforms are developing a reputation in the production industry as a patron for creativity, their productions are well-funded and have limited input from development executives. Netflix and Amazon are attracting some of the biggest stars to their platform from David Fincher (House of Cards, Mindhunter) to Martin Scorsese (The Irishman) to Park Chan-Wook (The Handmaiden) and Woody Allen (Café Society). The volume of their output, in turn, made the market for content more competitive, as cable channels and major studios now have even more competition. SVOD is also not restricted to having a target audience at different times of the day, which is the case for terrestrial linear-television channels such as the BBC or ITV. Viewers of SVOD get the complete freedom to choose what they want to watch, helped by Netflix’s complex recommendation algorithm, at anytime that is convenient.</p><br/>

          <img src='../../assets/pics/prepping/maninthehighcastle.jpg'/>
          <img src='../../assets/pics/prepping/mindhunter.jpg'/>

          <p>One of the major theme of the SVOD competition is that businesses need to invest tremendous amounts of capital into original programming, and while there are many ambitious companies vying to join the streaming market, it remains to be seen how many companies can successfully establish themselves. Microsoft’s Xbox Entertainment Studios (Deadline 2014), Snapchat’s Snap Channel (Deadline 2015) and Vimeo’s SVOD service (Deadline 2017) were all scrapped without explanation. The companies admitted that they would prefer to focus on their primary business model and original goals. Some suspected that the financial investments involved to stay competitive with Netflix and Amazon are simply too great (Major Studio 2017). With the barrier of entry to SVOD so high, the potential for new players entering the market is quite low. However, the rest of the tech conglomerates within the so-called FAANG, which stands for the most popular and best performing tech companies: Facebook, Amazon, Apple, Netflix and Google (Marketwatch 2017), has both the user base and capital to develop a service that can reach a huge audience. As for Hollywood majors, Disney is preparing to launch their own SVOD service, pulling their content away from their agreement with Netflix, which ends in 2019. The new streaming service will feature all of Disney and Pixar’s original movies, PVOD of new releases as well as new original content (Wired 2017). The programming focus will be for children, a demographic that has not yet been fully catered to on other streaming services. With the brand’s historical significance and recognition in children’s movies and television, the new platform could see Disney filling the void of children SVOD and becomes a huge streaming giant comparable to Netflix and Amazon (Forbes 2017). </p><br/>

          <p>The new-found SVOD influence presented itself as a disruption to the status quo since 2007 when Netflix introduced their streaming service (Business Insider 2017). Virginia Crisp suggested the use of the metaphor of an ‘hourglass effect’ can be used in relation to the traditional US studio-controlled distribution system. The metaphor meant that, while a large number of film production companies exist, ‘a small number of distributors reside at the centre of the hourglass controlling distribution to audience at the bottom of the structure’. (Crisp 2015: 23) This Hollywood model of film distribution dominated the market share before SVOD. Within the domestic market of US and Canada, major studios used to consistently earn more than 95% of the market share, with 65% in international territories (Blume 2006: 336). The introduction of SVOD has opened up production and distribution possibilities, and the US studio distribution system is no longer as dominant as it used to be.</p><br/>

          <img src='../../assets/pics/prepping/lionking.jpg'/>
          <img src='../../assets/pics/prepping/mickey.jpg'/>

          <p>One of the lucrative assets that major studios have is Intellectual property. For example, with Disney, they process many household names in their IP (Mickey Mouse, Lion King, Toy Story to name a few) and their ancillary business is by far the biggest compared to any studio, from retail and publishing to parks and resorts, they have a huge revenue chain directly linked to their IP, and so, they are able to negotiate lucrative licensing deals for the IP they process. With their proposed new SVOD service to rival Netflix and Amazon, it will showcase their vast amount of intellectual properties (Wired 2017). With Disney, Facebook and Apple investing in their own SVOD service, the market trend has shifted towards streaming services. According to a specialist at a major studio, most, if not all studios by now have a new department to specifically deal with SVOD as they are almost in daily contact with streaming services. To the benefit of the studios, streaming platforms have a wider reach of territories and it’s opened up new revenue streams in countries they haven’t been able to sell to previously (Major Studio 2017). And in many ways, it seems that the industry desperately needed their share of SVOD as much as anything. For Netflix and Amazon, Premium VOD on major studio’s platforms are a real competition, this is because it will draw box-office audiences from the newest releases to the PVOD platforms. However, the major studios are reluctant to commit to PVOD because of their existing relationship with their exhibition partners (Deadline 2017).</p><br/>


          <p>Theatrical windowing has been under scrutiny by the industry in recent years. Netflix run the day and date release if they can, which presents new feature film and quality television on their platforms in all territories simultaneously as well as theatrical, while Amazon likes to shorten the release window where they can, this will be looked into later on. For original films produced by these platforms, there is an argument about whether a film should have a wide theatrical release, one of the reason was piracy and this will be looked in more detail later. As for the economic incentives for a theatrical release, Macnab cited that it ‘was the engine that drove ancillary sales’ and those cinema showings were sometimes seen as a “‘loss leader’ and it’s the later profits that is really significant” (Macnab 2015). This point also resonated with independent distributors, for certain films they would expect losses in theatrical to boost VOD earnings (Fletcher 2017). This reasoning was mainly due to the fact that theatrical release only generate substantial revenue for well marketed films that attract a wide spectrum of audience. Recently the big winners in theatrical sales were superhero movies, action and sci-fi, movies such as The Avengers, Furious 7 and Star Wars: The Force Awakens (Box Office Mojo 2017) were immensely profitable in theatrical, but the market for middle to low budget films in theatrical have all but crashed (Fletcher 2017).</p><br/>

          <img src='../../assets/pics/prepping/avengers.jpeg'/>
          <img src='../../assets/pics/prepping/starwarsforce.jpg'/>


          <p>For major studios, more and more are adopting the day and date release model popularised by SVOD. By releasing feature films in theatres at the same time as streaming platforms in all territories, the increased access to films allows for consumers who couldn’t make a trip to the cinema due to commitments or low disposable income to view the film, and diminishes the need for consumers to download the content through illegal means. The standard theatrical window in the UK is 16 weeks theatrical and 6 months DVD/VOD afterward. The studios want to maximise the profitability during the period between theatrical release and streaming platforms, where the content is not available through legal channels. And studios are reluctant to publicly admit this window as undesirable at present because of the pressure from their theatrical partners (Deadline 2017), but according to the specialist at a major studio, day and date release is an optimal scenario. However, he also noted that unless the distributor owns the global rights, it is difficult to execute (Major Studio 2017), as they have to work with many other companies, as well as theatre-owners to negotiate the release.</p><br/>

          <p>There are varying successes and different reasons to use the day and date release model.  Rams is an Icelandic film distributed by Thunderbird Releasing in the UK, and managing director Edward Fletcher decided to go with day and date because he believed the method brings more attention in from the start and spread the film through word-of-mouth (Fletcher 2017). Rams, being a foreign language film, didn’t earn very much from domestic theatrical in the UK, but the international box office helped recoup the film completely (The Numbers 2017), and it was a notable success considering there was further revenue from VOD. Misconduct, a film starring Al Pacino and Anthony Hopkins, didn’t manage to recoup the budget with day and date (The Numbers 2017), however, the film suffered from a lack of marketing as well as very poor critical response (Rotten Tomatoes 2016). Curzon’s 45 Years was available on VOD and a limited theatrical run at the same time. Owning their own chain of cinemas, they can manage the day and date release seamlessly. The film achieved a seven-figure box office in the UK and was considered a huge success as it wasn’t shown in the multiplexes (The Numbers 2015).</p><br/>

          <img src='../../assets/pics/prepping/rams.jpg'/>
          <img src='../../assets/pics/prepping/45years.jpg'/>

          <p>The SVOD business has not only introduced major platforms such as Netflix and Amazon, but also smaller platforms that capitalise on offering a specific niche. Within the arthouse, independent niche there are two examples of SVOD services, Mubi and Filmstruck. Mubi, a streaming platform that shows a constantly rotating lineup of international and art house cinema, has a new film appear on the site every day and available to watch for 30 days only. Filmstruck, a collaboration between Turner Classic Movies and The Criterion Collection, is a streaming platform with a large library of classic and arthouse cinema, the subscription offers access to the complete Criterion Collection. The two arthouse SVOD platforms may be seen as direct competition, but they have very different business models, as Mubi business analyst Mueller noted, Filmstruck uses the same free-exploration unlimited viewing model that Netflix uses, while Mubi curates its own selection of movies. The former also focuses on archive releases from well-known directors whereas the latter focuses on newer independent and arthouse releases (Mueller 2017). Elsewhere, Vimeo maintains the niche for ad-free video-hosting and tools for filmmakers which has a premium subscriber base of 710,000 and monthly view count of 280 million (Expanded Ramblings 2017). The varying business models are an example of how OTT services can establish themselves within the SVOD marketplace with innovative offerings.</p><br/>

          <p>For Transactional VOD, Apple is the big winner with iTunes dominating the marketplace, although Amazon is not far behind (Wall Street Journal 2017). In the early days of TVOD, Apple went to major studios and offered advantageous deals to sell their movies (Major Studio 2017), since then they have maintained a strong relationship with the industry. With the store’s built-in access within the popular Apple devices, the platform is highly convenient to the masses. However this section of the VOD market is not very complicated, and competition may arise very quickly to change things around if a better curated or more well-defined site becomes available, although Apple should have the funds to improve the site significantly when they need to. TVOD also has the conveniency of being the earliest platform for consumers to legally watch the newest releases, especially for content that isn’t available on SVOD.</p><br/>

          <p>Independent distributors are also being affected by SVOD. What used to be a successful business model selling content to television and DVDs is now taken over by everyone selling to SVOD, and studios have an advantage with their multiple agreements over the independents (Nerger 2017). Also, with independent films being one of indie distributors’ main focus, the recent market trend shift to SVOD has pushed down demand for theatrical presentation of independent films. Caffrey noted that it is extremely rare for Independent films in the UK to recoup their budget. Producers often give up their percentage of the budget and hope for a success to recoup (Caffrey 2017), but as most films do not earn enough, it is not easy to be an independent producer in the UK. On very rare occasions, however, quality independent movies such as Lady Macbeth, fueled by great reviews, could make a success out of its theatrical run. Fletcher noted that for any rising star actor in the UK, US is the destination at their earliest chance, causing a constant talent drain in UK indie production. He suggested that for an indie film to be successful, the filmmaker has to be very bold and innovative, and not follow the traditions of television or theatre, which the UK has great resources in. Fletcher was the co-founder of Soda Pictures, a successful UK independent distributor for 12 years. In 2014 they were acquired by Canadian media giants Thunderbird Entertainment and subsequently was rebranded as Thunderbird Releasing. With the support of the media enterprise, the company became more capitalized, rebranded and repositioned as well as having more operational security (Fletcher 2017). While it is not uncommon for larger companies to acquire smaller independent companies, the larger studios benefit from the brand image that they will associate themselves with. For independent production companies being acquired, their creative production team and the underlying intellectual property rights are all valuable assets for the larger enterprise, as they have a potential to develop more revenue streams down the line (Major Studio 2017).</p><br/>

          <p>From a producer’s point of view, selling streaming rights to SVOD is definitely something to consider. Andrew Nerger noted that The Movie Partnership, an all-rights digital aggregator in the UK, pitches a collection of ideas to Netflix about 4 times or more a year (Nerger 2017). With Netflix Originals being a popular brand at present, working with Netflix is desirable. Similarly, Amazon is also developing their own Amazon Originals, and with the addition of Facebook and Apple investing in original content, the increased competition will open up a lot of financing options for content producers. Excluding SVOD, television series are generally more stable economically compared to feature film, as cable and terrestrial television channels can fund a portion of the budget as well as giving distribution guarantees (Caffrey 2017), in addition, the content will also have strong viewing potential when broadcast on their channel. Currently, making an independent film in the UK is economically very risky, unless it can be picked up by an SVOD service. Other than the major revenue channels with cable television and streaming platforms, selling content on iTunes will be a logical next step, given the producer retained the rights to distribute on TVOD. Once the producer have exhausted all the paid-consumer avenues, monetizing the content through Youtube and AVOD will give the producer a small revenue over time, although the exclusivity of the film will be non-existent at this point.</p><br/>

          <div className='conclusion-title'>Conclusion</div>

          <p>Video on demand has presented itself as a market with huge potential for businesses and producers alike. With Netflix and Amazon leading the SVOD marketplace, several other major conglomerates with significant capital are entering the VOD sandbox such as Facebook and Disney. The competition will be fierce, and to the benefit of filmmakers and producers, there is now more demand than ever for original ideas by the major SVOD platforms, as they are eager to build their catalogue of intellectual properties. For Independent distributors, maintaining a profitable relationship with SVOD will be key. Similarly, for producers developing an independent film, it is preferable to have a distribution deal with a streaming service before entering production. As the consumers are shifting their focus onto the more convenient VOD, the business ecosystem will benefit from adapting to the changes.</p><br/>

          <a className='nextchapter' href='./Social'>Next Chapter</a>

        </div>
      </div>
    )
  }
}

export default Prepping
