import React from 'react'

class Ultraviolet extends React.Component{
  constructor(){
    super()

    this.state ={}
  }

  render(){
    return(
      <div className='ultraviolet'>
        <div className='section-title'>Ultra-Violet, Piracy and (Potential Death of) the Cinematic Experience</div>
        <div className='text'>

          <img src='../../assets/pics/uv/ultraviolet.jpeg'/>
          <img src='../../assets/pics/uv/chinapiracy.jpg'/>

          <p>When Ultra-Violet was introduced in 2010 by the DECE (Digital Entertainment Content Ecosystem), a consortium of the major studios, retailers, cable operators and hardware manufacturers, the digital rights locker was created as a legal digital alternative to pirated content that can be controlled by the collective efforts by the industry. Ultra-Violet works as an universal certificate for digital rights of a particular piece of content, playable on specific Ultra-Violet digital players and apps, and keeps track of purchases that the consumer had redeemed. However, a range of factors hindered its popularity. The cost of becoming a member of Ultra-Violet is too high for independent companies (Nerger 2017), which limited the spread of the system, while the conversion rate of Ultra-Violet is very low, at less than 20% of the people who purchased Ultra-Violet DVDs (Major Studio 2017). One of the major stumbling blocks is  platform restriction, there are more than ten different possible platforms to play Ultra-Violet content, and each platform only allows the consumer to play it if they have redeemed it on the platform specifically. Unlike DVDs and Blu-rays which are playable on every platform and media player, this platform-restricted system didn’t provide a more convenient option. </p><br/>

          <p>Nonetheless, Ultra-Violet and various DRM systems implemented by businesses are trying to restrict the ever-present leech of pirated content, and piracy itself is a topic of much debate. Ramon Lobato suggests that as ‘legal boundaries around media distribution expand and contract, so do the pirate markets’ and what is defined as legal activity changes accordingly (Lobato 2012: 88). Also it is worth noting that not all territories had been changed by online distribution in a consistent manner, and for some markets where film culture is generally less developed, he argues that ‘piracy is not only a form of deviant behaviour but may offer routes to knowledge and development’ (Lobato 2008: 16). </p><br/>

          <p>China, the country with the highest piracy rate (MPA 2006), has been reluctant to adopt a Western system of copyright protection. Oliver Ting claimed that piracy in China is due to economic and political circumstances rather than cultural ones. Beijing has little power over local governments, and the local governments have little incentive to curtail piracy as it ‘provides vast numbers of people with regular employment’ while law enforcement only prosecutes ‘for profit’ piracy (Ting 2007: 410). China’s specific foreign films quota, which to date allows only 34 overseas films (Hollywood Reporter 2017) is also a tremendous boon for film pirates in the country, who essentially have a monopoly on foreign content (Ting 2007: 413) until there are legal means for consumers to obtain the titles in China.</p><br/>


          <p>Piracy in Russia is also running rampant, according to a survey by Irdeto, a software technology developer, two in three respondents in Russia believe that it is not illegal to download or stream pirated video content (Irdeto 2017). Film distributor networks in Russia, such as the Warner-affiliated Kapo network, saw 15 to 30 percent loss in income due to piracy (Moscow Times 2017) and the Russian government is under pressure to impose stricter anti-piracy laws. However, the country historically has strong resistance from the public. The 2013 Russian anti-piracy law, which allows court orders to block websites with alleged offending content upon request of the copyright owner, provoked a huge backlash. NGO Roskomsvoboda and political group The Pirate Party of Russia are both prominent groups in the country advocating for the freedom of information and privacy on the internet. They were infuriated by the vague wording of the terms in the new law and believed it will stifle online innovation. The groups set up a petition to demand a repeal of the law and 2000 websites participated in the internet strike (Calvert Journal 2013). </p><br/>

          <img src='../../assets/pics/uv/roskom.jpeg'/>
          <img src='../../assets/pics/uv/sopawiki.png'/>

          <p>This protest in Russia was similar to the 2012 mass protests against SOPA (Stop Online Piracy Act) and PIPA (Protect Intellectual Property Act) in the US. The two bills, if enacted, would have led some websites to be censored based on accusations of copyright infringement. The internet strike was joined by over 115,000 websites including Wikipedia, Google, Twitter and Reddit. During the strike, the websites made their services temporarily unavailable as well as putting up notices raising awareness for the bills to visitors, many of the websites had direct links for people to contact their local government representatives (Sopa Strike 2012). Almost overnight, many of the bill’s legislators and sponsors withdrew their support for the bills. And while the SOPA and PIPA protests succeeded in pressuring Congress to drop the bills, the Duma passed theirs within three weeks, ratified by President Putin. Anton Nossik noted that the legislators completely refused to consult the wider industry in drafting the law (Calvert Journal 2013).</p><br/>

          <p>The wide ranging circumstances in copyright laws from China to Russia present challenges in tackling piracy on a worldwide scale. However, theatrical and digital release windows have been shortening in recent years in an effort to limit the incentive for illegal downloads. Alexander Rodnyansky, the producer of Leviathan, a Russian 2014 Palme d’Or contender, acknowledged that the film suffered immense pirating in Russia. Leviathan was downloaded 10 million times on pirated sites before official release and achieved a meagre worldwide theatrical run of $1.7 million (The Numbers 2017). The film’s theatrical release had been delayed due to the awards campaign in the US (Variety 2017). Having learnt from the experience, Rodnyansky’s next film, Loveless, was released in Russia immediately after Cannes to protect the theatrical earnings from piracy in the country (Screendaily 2017).</p><br/>

          <img src='../../assets/pics/uv/leviathan.jpeg'/>
          <img src='../../assets/pics/uv/loveless.jpg'/>

          <p>In 2013, Sony Entertainment and Disney tested Premium VOD release in South Korea. The country had a high level of piracy in both online and physical, and DVD sales in the country had not been very profitable (Wall Street Journal 2013). The two studios offered selected films still-in-theatres on Premium VOD, titles such as Django Unchained and Wreck-It Ralph were made available on PVOD three to five weeks after theatrical debut. The price for PVOD was slightly higher than a cinema ticket, but its buy rates were 30% higher than of other titles (Variety 2013).  One of the crucial advantages of Premium VOD is the product experience, and Fletcher believed that by making sure the product is worth buying for, consumers will have little reason to settle for a less impressive experience in pirated content (Fletcher 2017). The experiment had given major studios confidence to consider PVOD as a method to be employed worldwide (Major Studio 2017). However, the industry as a whole has not come to a consensus on the matter at present (Deadline 2017).</p><br/>

          <img src='../../assets/pics/uv/django.jpg'/>
          <img src='../../assets/pics/uv/wreckit.jpeg'/>

          <p>The benefits of short release windows are apparent in relation to piracy, as it offers accelerated access to the latest releases. However, the release method poses a huge threat to theatre chains, as they see the window as their main source of income. Netflix has always maintained their release policy to ensure the content is available on their platform first. Following the disappointing theatrical run of Beasts of No Nation (Deadline 2015), the company refused to release Cannes entries Okja and The Meyerowitz Stories in French theatres, which led to Cannes being pressurized to disqualify streaming-only films with no theatrical release in France in the future (The Verge 2017). France also notably has a law that prevents films released in French theatres from playing on SVOD platforms in the country for three years (Deadline 2017), which is something Netflix cannot accept. The developments at the festival added to the ongoing debate about the future of theatrical presentation, with some commenting that Netflix’s strategy may demean the medium of movie theatres and ultimately hurt the business (Quartz 2017). While Netflix has an apparent disregard for theatrical presentation, not all of their films are streaming-only. With the 2016 film Under the Shadows, Netflix bought worldwide streaming rights to the film at Sundance, however the film’s producers felt it was necessary for the film to have a theatrical life, so they reserved a 90-days window to exploit the theatrical window, and this went to Vertigo Entertainment in the UK and XYZ Films in the US, before Netflix can show it on SVOD. According to Ed Caffrey from Vertigo Releasing, Netflix didn’t want to buy the theatrical rights as they see no reason to invest beyond streaming on their service (Caffrey 2017). </p><br/>

          <img src='../../assets/pics/uv/meyerowitz.jpg'/>
          <img src='../../assets/pics/uv/salesman.jpg'/>

          <p>Christopher Nolan has been a strong critic of Netflix’s release strategy, he suggested that the platform’s investment in creative, original content has been overshadowed by it being used as leverage against theatre businesses, and that the day and date release model is untenable for theatrical presentation (Indiewire 2017). On the other hand, Ava DuVernay acknowledged that not all regions around the world have access to a movie theatre, so theatrical doesn’t reach as wide an audience as SVOD (The Atlantic 2017). Will Smith also suggested that day and date release and theatrical release are two different viewing experiences, and that certain content that works on Netflix might not work on theatrical (Polygon 2017).</p><br/>

          <p>In the same interview with Indiewire, Nolan supported Amazon’s release strategy, which has taken a more considered approach with theatrical sales. Their Oscar-winning Manchester by the Sea was given a full 90 days theatrical run before it was made available to Amazon Prime subscribers. The platform still preferred to shorten their theatrical windows for some films, such as Chi-Raq and Creative Control which were theatre-exclusive for only two months (Mashable 2016), but for major award contenders such as The Salesman, Paterson and Manchester by the Sea, the platform opted to have the traditional theatrical window. Following the standard practice seemed to have paid off for Amazon in the industry, with Manchester by the Sea and The Salesman both winning Oscars. While Netflix has yet to be nominated with any of its feature films at the Academy Awards (Hollywood Reporter 2017). </p><br/>


          <p>The surge in popularity in streaming platforms also brought about a new viewing experience for television dramas in binge watching. Contrary to the age-old system of one-episode-a-week long established by cable channels, Netflix and Amazon’s television series are available to stream in its entirety on release. Vince Gilligan, the showrunner of Breaking Bad, argued that episodic release is a better viewing method for the audience, as it allowed better opportunity to digest and ponder the concepts of each episode (News.com.au 2017). Matthew Weiner of Mad Men also expressed a similar opinion in that he would argue for a weekly scheduling if he was to produce a series on Netflix (New York Times 2015). On the other hand, some suggested that Netflix has came to expose and take advantage of the limitations of traditional television. Richard Greenfield, media analyst at BTIG, noted that once consumers started watching shows with no commercials, they will be reluctant to switch back. He also argued that waiting each week for the next episode of a favourite show is no longer a good experience for consumers (New York Times 2016). Ultimately, Episodic release and the whole-season binge watching presented two different ideologies, the former allows time for the viewer to contemplate the story developments between each episode, while the latter offers a seamless, immersive experience from beginning to end. It remains to be seen whether one release method will overtake another.</p><br/>

          <img src='../../assets/pics/uv/breakingbad.jpg'/>
          <img src='../../assets/pics/uv/madmen.jpg'/>
          
          <p>As for theatrical presentation, global box office suggests that box office revenues are still highly profitable (Variety 2017), but the rise in ticket prices masked the problem that cinema attendance has been stagnating (The Verge 2017), as consumers continue to explore options to view content through SVOD and TVOD. But since the beginning of movie theatres, there has always been the idea that a visit to the cinema presented a sense of comfort and escape (Macnab 2015). Martin Scorsese believes that cinema theatres will always be there for the communal experience (LWR 2017). Jerry Bruckheimer felt the same (ABC 2017), comparing going to the theatres as having a meal outside of home. Caffrey believes that cinemas will never die, but may become more of a speciality similar to stage theatre (Caffrey 2017).</p><br/>

          <div className='conclusion-title'> Conclusion</div>

          <p>While Ultra-Violet may not be the answer to illegal content, studios are working towards a more effective solution (Major Studio 2017). Nerger noted that ‘Piracy is like a hydra, if you cut off one of its head, there’s another one’ (Nerger 2017), while Fletcher emphasised that it is simply human nature to want things for free (Fletcher 2017). Unfortunately, the presence of piracy may never be extinguished completely. The difference in copyright laws in countries around the world such as China and Russia also prevented worldwide regulation from being universally maintained. But the industry’s new release strategies such as PVOD will limit the need for illegal downloads and allow businesses to obtain more profits. It remains to be seen whether Netflix’s streaming-exclusive method of release will continue amid opposition from the film industry and its feature films unable to be recognised for major awards. Within the age of video on demand, subscription platforms, streaming rentals, theatrical viewing and VOD on mobile devices present many new viewing experiences for the consumer to watch content at their own preference, and ultimately, they are the ones being benefited the most.</p><br/>

          <a className='nextchapter' href='./Virtual'>Next Chapter</a>
        </div>
      </div>
    )
  }
}
export default Ultraviolet
